### ISSUE TITLE
Feedback from Milestone 2

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/Workflows_showcase#75]
Wasn't too sure what Figure 1's x axis ticks are representing at first glance.
Would be nice to make the table sizes a bit more similar.
Maybe a model comparison summary using a bar plot will be more effective.
Probably move your main function in your code to the top and comment some code inside your functions.
Probably only table 3 (not table 2) needs to be included in the final report. The key numbers from table 2 could be easily communicated inline in the text.
Table 3 should use human-sensible feature names, not column names (what is gsm, I already forget by this point in the report).
Was anything done based on what you found in table 3? Did you drop features? Rows? If you include a table or figure, you need to explain why it's important and what the takeaway was from it.
I feel like the Feature Transformation and Encoding section should come before model comparisons and model choice. This might address my comment above.
Not sure if the reader wants to know all 10 metrics about your best model. Highlight the most 2-3 important metrics, explain what they are and what it means for your model (and how well you can answer your question). Figure 2 (which is really a table and should be labelled as such) might be more interesting you put the dummy classifier side by side the optimized model. Perhaps side by side the non-optimized random forest as well. Also, what is score? Is it accuracy? F1 score? Similar to my comments on other tables, text in tables should be human sensible and not column names or default arguments names.

**Comment by ssyayayy** [comment]
Thanks for your valuable feedback! We have addressed them all. Here are the details:

- [X] Wasn't too sure what Figure 1's x axis ticks are representing at first glance. 
- Fixed the figure
- [X] Would be nice to make the table sizes a bit more similar.
- Improved table sizes.
- [X] Maybe a model comparison summary using a bar plot will be more effective.
- We do not have time to rebuild it but good suggestion! We have included in the future direction section.
- [X] Probably move your main function in your code to the top and comment some code inside your functions.
- Moved main function to the top, and added comments.
- [X] Probably only table 3 (not table 2) needs to be included in the final report. The key numbers from table 2 could be easily communicated inline in the text.
- Agreed and removed table2.
- [X] Table 3 should use human-sensible feature names, not column names (what is gsm, I already forget by this point in the report).
- Good point. Considered this change may break our tested make file, we add a description right after that table to reiterate what `gsm` represents.
- [X] Was anything done based on what you found in table 3? Did you drop features? Rows? If you include a table or figure, you need to explain why it's important and what the takeaway was from it.
- Added takeaways
- [X] I feel like the Feature Transformation and Encoding section should come before model comparisons and model choice. This might address my comment above.
- Moved it up to the data overview section.
- [X] Not sure if the reader wants to know all 10 metrics about your best model. Highlight the most 2-3 important metrics, explain what they are and what it means for your model (and how well you can answer your question). Figure 2 (which is really a table and should be labelled as such) might be more interesting you put the dummy classifier side by side the optimized model. Perhaps side by side the non-optimized random forest as well. Also, what is score? Is it accuracy? F1 score? Similar to my comments on other tables, text in tables should be human sensible and not column names or default arguments names.
- Labeled Figure 2 as table 2, reduced the size of the metrics. We use accuracy for scoring. Improved the formatting.
